[install]
# Use exact versions for better reproducibility
exact = true

[install.scopes]
# Configure any scoped packages if needed

[test]
# Test configuration for Bun
preload = ["./test/setup.ts"]

[run]
# Runtime configuration
bun = true
